name: SmallRye Build

on:
  push:
    branches: 
      - master
    paths-ignore:
      - '.gitignore'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'NOTICE'
      - 'README*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: AdoptOpenJDK/install-jdk@v1
        name: Set up JDK 11
        with:
          version: 11

      - name: Maven
        run: mvn -B formatter:validate verify --file pom.xml
